droneci: upgrade twine
- this is just to get rid of the pipeline failing at pypi publish w/
  > ERROR    InvalidDistribution: Metadata is missing required fields: Name,Version"

- also note without --ignore-installed flag the upgrade throws
  > ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and
    thus we cannot accurately determine which files belong to it which would lead
    to only a partial uninstall